const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const bgCanvas=$('#bgCanvas'),wishCanvas=$('#wishCanvas'),sceneCanvas=$('#sceneCanvas');
const bgCtx=bgCanvas.getContext('2d'),wishCtx=wishCanvas.getContext('2d'),sceneCtx=sceneCanvas.getContext('2d');
const DB_NAME='WishingSkyDB',DB_VERSION=1,STORE_WISHES='wishes',STORE_META='meta';
let db=null,W=innerWidth,H=innerHeight,DPR=Math.min(devicePixelRatio||1,2),farStars=[],frontStars=[],shooting=[],particles=[],floating=[],saved=[],pointer={x:W/2,y:H/2,tx:0,ty:0},mood='平靜',audioCtx,ambient,ambientOn=false,deferredPrompt=null,breathTimer=null,breathOn=false,currentTab='stats';
const moods=[['平靜','🌙'],['感謝','✨'],['想念','🫧'],['放下','🍃'],['勇氣','🕯️'],['疲憊','☁️']];
const themeNames={midnight:'深夜藍',mist:'晨霧白',forest:'森林綠',rose:'玫瑰夜空'};
const achievements=[
 {id:'firstWish',icon:'🌟',title:'第一顆星',desc:'寫下第一個心願',test:w=>w.length>=1},
 {id:'firstLetGo',icon:'🍃',title:'第一次放下',desc:'第一次選擇「放下」',test:w=>w.some(x=>x.mood==='放下')},
 {id:'firstGratitude',icon:'✨',title:'第一次感謝',desc:'第一次選擇「感謝」',test:w=>w.some(x=>x.mood==='感謝')},
 {id:'sevenDayStreak',icon:'🕯️',title:'連續 7 天許願',desc:'連續 7 天都有種下星星',test:w=>streakDays(w)>=7},
 {id:'tenStars',icon:'🌌',title:'小小銀河',desc:'累積 10 顆心願星星',test:w=>w.length>=10}
];
function openDB(){return new Promise((resolve,reject)=>{const req=indexedDB.open(DB_NAME,DB_VERSION);req.onupgradeneeded=e=>{const d=e.target.result;if(!d.objectStoreNames.contains(STORE_WISHES)){const s=d.createObjectStore(STORE_WISHES,{keyPath:'id'});s.createIndex('createdAt','createdAt',{unique:false});s.createIndex('mood','mood',{unique:false});s.createIndex('dateKey','dateKey',{unique:false});}if(!d.objectStoreNames.contains(STORE_META))d.createObjectStore(STORE_META,{keyPath:'key'});};req.onsuccess=()=>resolve(req.result);req.onerror=()=>reject(req.error);});}
function tx(store,mode='readonly'){return db.transaction(store,mode).objectStore(store)}
function reqToPromise(req){return new Promise((res,rej)=>{req.onsuccess=()=>res(req.result);req.onerror=()=>rej(req.error)})}
async function getAllWishes(){return (await reqToPromise(tx(STORE_WISHES).getAll())).sort((a,b)=>new Date(a.createdAt)-new Date(b.createdAt))}
async function putWish(w){await reqToPromise(tx(STORE_WISHES,'readwrite').put(w))}
async function clearWishes(){await reqToPromise(tx(STORE_WISHES,'readwrite').clear())}
async function putMeta(key,value){await reqToPromise(tx(STORE_META,'readwrite').put({key,value}))}
async function getMeta(key,def=null){const row=await reqToPromise(tx(STORE_META).get(key));return row?row.value:def}
function todayKey(d=new Date()){return d.toLocaleDateString('sv-SE')}
function resize(){W=innerWidth;H=innerHeight;DPR=Math.min(devicePixelRatio||1,2);[bgCanvas,wishCanvas,sceneCanvas].forEach(c=>{c.width=W*DPR;c.height=H*DPR;c.style.width=W+'px';c.style.height=H+'px'});[bgCtx,wishCtx,sceneCtx].forEach(c=>c.setTransform(DPR,0,0,DPR,0,0));createStars();drawSaved()}addEventListener('resize',resize);
function createStars(){farStars=[];frontStars=[];for(let i=0,n=Math.floor(W*H/5200);i<n;i++)farStars.push({x:Math.random()*W,y:Math.random()*H,r:Math.random()*1.1+.25,a:Math.random()*.45+.18,s:Math.random()*.025+.006,p:Math.random()*7});for(let i=0,n=Math.floor(W*H/10500);i<n;i++)frontStars.push({x:Math.random()*W,y:Math.random()*H,r:Math.random()*1.7+.5,a:Math.random()*.5+.25,d:Math.random()*1.8+.7})}
function star(ctx,x,y,r,a=1){const g=ctx.createRadialGradient(x,y,0,x,y,r*8);g.addColorStop(0,`rgba(255,255,255,${.95*a})`);g.addColorStop(.18,`rgba(224,235,217,${.65*a})`);g.addColorStop(.55,`rgba(159,181,194,${.22*a})`);g.addColorStop(1,'rgba(255,255,255,0)');ctx.save();ctx.globalCompositeOperation='lighter';ctx.fillStyle=g;ctx.beginPath();ctx.arc(x,y,r*8,0,7);ctx.fill();ctx.fillStyle=`rgba(255,255,255,${.95*a})`;ctx.beginPath();ctx.arc(x,y,r,0,7);ctx.fill();ctx.restore()}
function drawSaved(){wishCtx.clearRect(0,0,W,H);saved.forEach((w,i)=>{const x=w.xRatio*W,y=w.yRatio*H;star(wishCtx,x,y,w.r||4,.9); if(i>0){const p=saved[i-1],px=p.xRatio*W,py=p.yRatio*H;wishCtx.save();wishCtx.globalAlpha=.16;wishCtx.strokeStyle='rgba(205,226,216,.75)';wishCtx.lineWidth=1;wishCtx.setLineDash([2,8]);wishCtx.beginPath();wishCtx.moveTo(px,py);wishCtx.lineTo(x,y);wishCtx.stroke();wishCtx.restore();}})}
function bg(t){bgCtx.clearRect(0,0,W,H);farStars.forEach(s=>{const a=Math.max(.05,s.a+Math.sin(t*s.s+s.p)*.22);bgCtx.fillStyle=`rgba(255,255,255,${a})`;bgCtx.beginPath();bgCtx.arc(s.x,s.y,s.r,0,7);bgCtx.fill()});pointer.tx+=((pointer.x-W/2)/W-pointer.tx)*.035;pointer.ty+=((pointer.y-H/2)/H-pointer.ty)*.035;frontStars.forEach(s=>{bgCtx.fillStyle=`rgba(255,255,255,${s.a})`;bgCtx.beginPath();bgCtx.arc(s.x-pointer.tx*34*s.d,s.y-pointer.ty*24*s.d,s.r,0,7);bgCtx.fill()})}
function shoot(x,y){const ang=-Math.PI/5,sp=Math.random()*4+8;shooting.push({x,y,vx:Math.cos(ang)*sp,vy:Math.sin(ang)*sp,life:1,trail:[]});chime()}function updateShooting(){sceneCtx.save();sceneCtx.globalCompositeOperation='lighter';shooting=shooting.filter(s=>{s.trail.push({x:s.x,y:s.y,l:s.life});if(s.trail.length>22)s.trail.shift();s.x+=s.vx;s.y+=s.vy;s.life-=.018;for(let i=0;i<s.trail.length-1;i++){let a=i/s.trail.length*s.life,p=s.trail[i],q=s.trail[i+1];sceneCtx.strokeStyle=`rgba(215,235,255,${a*.55})`;sceneCtx.lineWidth=2.4*a+.4;sceneCtx.lineCap='round';sceneCtx.beginPath();sceneCtx.moveTo(p.x,p.y);sceneCtx.lineTo(q.x,q.y);sceneCtx.stroke()}star(sceneCtx,s.x,s.y,2.7,s.life);return s.life>0&&s.x<W+120&&s.y>-120});sceneCtx.restore()}
function burst(x,y,col='rgba(218,232,221,'){for(let i=0;i<52;i++){const a=Math.random()*7,sp=Math.random()*2.2+.4;particles.push({x,y,vx:Math.cos(a)*sp,vy:Math.sin(a)*sp,r:Math.random()*2+.7,life:1,decay:Math.random()*.014+.01,col})}}function updateParticles(){sceneCtx.save();sceneCtx.globalCompositeOperation='lighter';particles=particles.filter(p=>{p.x+=p.vx;p.y+=p.vy;p.vx*=.99;p.vy*=.99;p.life-=p.decay;sceneCtx.fillStyle=`${p.col}${Math.max(0,p.life)})`;sceneCtx.beginPath();sceneCtx.arc(p.x,p.y,p.r*p.life,0,7);sceneCtx.fill();return p.life>0});sceneCtx.restore()}
function floatWish(text){const sx=W/2,sy=H/2+18,ex=W*(.18+Math.random()*.64),ey=H*(.12+Math.random()*.42);floating.push({text,sx,sy,ex,ey,t:0,s:.0065,done:false});burst(sx,sy);ascend()}function ease(t){return t<.5?4*t*t*t:1-Math.pow(-2*t+2,3)/2}function lerp(a,b,t){return a+(b-a)*t}async function createWish(text,x,y){const item={id:(crypto.randomUUID?crypto.randomUUID():Date.now()+''+Math.random()),text,mood,xRatio:x/W,yRatio:y/H,r:Math.random()*2+3.2,createdAt:new Date().toISOString(),dateKey:todayKey()};await putWish(item);saved.push(item);drawSaved();renderAllJournal();checkAchievements();return item}
function updateFloating(){sceneCtx.save();sceneCtx.globalCompositeOperation='lighter';floating=floating.filter(o=>{o.t+=o.s;let t=Math.min(o.t,1),e=ease(t),x=lerp(o.sx,o.ex,e),y=lerp(o.sy,o.ey,e),sc=lerp(1,.08,e),a=1-Math.max(0,t-.72)/.28;sceneCtx.save();sceneCtx.translate(x,y);sceneCtx.scale(sc,sc);sceneCtx.font='500 22px system-ui,"Noto Sans TC"';sceneCtx.textAlign='center';sceneCtx.textBaseline='middle';sceneCtx.fillStyle=`rgba(255,255,255,${a*.88})`;sceneCtx.shadowColor=`rgba(220,235,255,${a})`;sceneCtx.shadowBlur=16;sceneCtx.fillText(o.text,0,0);sceneCtx.restore();star(sceneCtx,x,y,3.2+t*2,Math.min(1,t*1.4));if(Math.random()<.35)particles.push({x:x+(Math.random()-.5)*22,y:y+(Math.random()-.5)*22,vx:(Math.random()-.5)*.4,vy:Math.random()*-.5-.1,r:Math.random()*1.6+.4,life:.65,decay:.015,col:'rgba(230,238,225,'});if(t>=1&&!o.done){o.done=true;createWish(o.text,o.ex,o.ey).then(()=>burst(o.ex,o.ey,'rgba(205,226,216,'));}return t<1});sceneCtx.restore()}
function findWish(x,y){for(let i=saved.length-1;i>=0;i--){const w=saved[i],wx=w.xRatio*W,wy=w.yRatio*H;if(Math.hypot(x-wx,y-wy)<=Math.max(18,(w.r||4)*4))return {...w,screenX:wx,screenY:wy,index:i}}return null}function tooltip(w){const el=$('#wishTooltip');if(!w){el.classList.remove('show');return}el.textContent=`${w.mood||'心願'}｜${w.text}`;el.style.left=w.screenX+'px';el.style.top=w.screenY+'px';el.classList.add('show')}
function openPanel(){$('#wishPanel').classList.add('show');$('#wishPanel').setAttribute('aria-hidden','false');setTimeout(()=>$('#wishInput').focus(),200)}function closePanel(){$('#wishPanel').classList.remove('show');$('#wishPanel').setAttribute('aria-hidden','true');$('#wishInput').value=''}function submit(){const text=$('#wishInput').value.trim();if(!text)return $('#wishInput').focus();closePanel();floatWish(text)}
function renderMood(){const row=$('#moodRow');row.innerHTML='';moods.forEach(([m,e])=>{const b=document.createElement('button');b.className='mood-chip'+(m===mood?' active':'');b.textContent=`${e} ${m}`;b.onclick=()=>{mood=m;renderMood()};row.appendChild(b)})}
function byMood(){return saved.reduce((a,w)=>(a[w.mood||'未分類']=(a[w.mood||'未分類']||0)+1,a),{})}function escapeHtml(s=''){return s.replace(/[&<>"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]))}function streakDays(wishes=saved){const keys=[...new Set(wishes.map(w=>w.dateKey||todayKey(new Date(w.createdAt))))].sort().reverse();let count=0,d=new Date();while(keys.includes(todayKey(d))){count++;d.setDate(d.getDate()-1)}return count}
function renderStats(){const box=$('#tab-stats'),today=todayKey();const dayCount=saved.filter(w=>(w.dateKey||todayKey(new Date(w.createdAt)))===today).length,total=saved.length,moodsMap=byMood(),maxMood=Math.max(1,...Object.values(moodsMap));const recent=saved.slice(-6).reverse();box.innerHTML=`<div class="stat-card"><strong>今日種下</strong><div style="font-size:34px;margin-top:4px">${dayCount} 顆</div><small>全部累積 ${total} 顆｜目前連續 ${streakDays()} 天</small></div><div class="stat-card"><strong>心情分佈</strong>${Object.entries(moodsMap).map(([k,v])=>`<div style="margin-top:10px">${k} <small>${v}</small><div class="bar"><i style="width:${v/maxMood*100}%"></i></div></div>`).join('')||'<p>還沒有資料</p>'}</div><div class="stat-card"><strong>最近的星星</strong>${recent.map(w=>`<p>・${w.mood||'心願'}｜${escapeHtml(w.text)}</p>`).join('')||'<p>今晚的第一顆星，等你點亮。</p>'}</div>`}
function renderCalendar(){const box=$('#tab-calendar'),now=new Date(),y=now.getFullYear(),m=now.getMonth();const first=new Date(y,m,1),days=new Date(y,m+1,0).getDate(),lead=first.getDay();const counts={};saved.forEach(w=>{const k=w.dateKey||todayKey(new Date(w.createdAt));counts[k]=(counts[k]||0)+1});let html=`<div class="stat-card"><strong>${y} 年 ${m+1} 月心情月曆</strong><p>星星越亮，代表那天留下越多心願。</p><div class="calendar">`;['日','一','二','三','四','五','六'].forEach(d=>html+=`<div class="dow">${d}</div>`);for(let i=0;i<lead;i++)html+='<div class="day empty"></div>';const max=Math.max(1,...Object.values(counts));for(let d=1;d<=days;d++){const key=todayKey(new Date(y,m,d)),n=counts[key]||0,a=n?Math.min(.95,.25+n/max*.7):.08;html+=`<div class="day" title="${key}｜${n} 顆"><span>${d}</span>${n?`<i class="spark" style="--a:${a};--n:${n}"></i>`:''}</div>`}html+='</div></div>';box.innerHTML=html}
function renderAchievements(){const box=$('#tab-achievements');box.innerHTML=achievements.map(a=>{const ok=a.test(saved);return `<div class="stat-card achievement ${ok?'unlocked':''}"><div class="badge">${a.icon}</div><div><strong>${a.title}</strong><p>${a.desc}${ok?'｜已解鎖':'｜尚未解鎖'}</p></div></div>`}).join('')}
function renderAllJournal(){renderStats();renderCalendar();renderAchievements()}let unlockedCache=new Set();async function checkAchievements(){const prev=await getMeta('unlockedAchievements',[]);unlockedCache=new Set(prev);const now=[];achievements.forEach(a=>{if(a.test(saved)){now.push(a.id);if(!unlockedCache.has(a.id))toast(`解鎖成就：${a.title} ${a.icon}`)}});await putMeta('unlockedAchievements',now)}
function storyFrom(index){if(saved.length<2)return null;const path=saved.slice(Math.max(0,index-4),index+1);return path.map((w,i)=>`${i+1}. ${w.mood||'心願'}：${w.text}`).join('\n')+'\n\n這些星星連起來，像是在提醒你：每一個片刻都沒有白費，夜會很深，光也會慢慢留下。'}
function toast(msg){const el=$('#toast');el.textContent=msg;el.classList.remove('hidden');clearTimeout(toast.t);toast.t=setTimeout(()=>el.classList.add('hidden'),2600)}
async function exportJSON(){const payload={app:'deep-night-wishing-sky',version:3,exportedAt:new Date().toISOString(),wishes:saved,theme:$('#themeSelect').value,achievements:await getMeta('unlockedAchievements',[])};const blob=new Blob([JSON.stringify(payload,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`wishing-sky-${todayKey()}.json`;a.click();URL.revokeObjectURL(a.href)}
async function importJSON(file){try{const payload=JSON.parse(await file.text()),incoming=Array.isArray(payload)?payload:(payload.wishes||[]);if(!Array.isArray(incoming))throw new Error('JSON 格式不正確');const map=new Map(saved.map(w=>[w.id,w]));incoming.forEach(w=>{if(w&&w.text){const id=w.id||Date.now()+Math.random()+'';map.set(id,{...w,id,dateKey:w.dateKey||todayKey(new Date(w.createdAt||Date.now())),createdAt:w.createdAt||new Date().toISOString(),xRatio:Math.min(1,Math.max(0,w.xRatio??Math.random())),yRatio:Math.min(1,Math.max(0,w.yRatio??Math.random())),r:w.r||4})}});await clearWishes();saved=[...map.values()].sort((a,b)=>new Date(a.createdAt)-new Date(b.createdAt));for(const w of saved)await putWish(w);drawSaved();renderAllJournal();checkAchievements();toast(`匯入完成：目前共 ${saved.length} 顆星星`)}catch(e){alert('匯入失敗：'+e.message)}}
function ensureAudio(){if(!audioCtx)audioCtx=new (AudioContext||webkitAudioContext)();if(audioCtx.state==='suspended')audioCtx.resume()}function startAmbient(){ensureAudio();const master=audioCtx.createGain();master.gain.setValueAtTime(.0001,audioCtx.currentTime);master.gain.exponentialRampToValueAtTime(.075,audioCtx.currentTime+1.2);const o1=audioCtx.createOscillator(),o2=audioCtx.createOscillator();o1.type='sine';o1.frequency.value=110;o2.type='triangle';o2.frequency.value=220;const g1=audioCtx.createGain(),g2=audioCtx.createGain();g1.gain.value=.22;g2.gain.value=.045;const len=audioCtx.sampleRate*2,buf=audioCtx.createBuffer(1,len,audioCtx.sampleRate),data=buf.getChannelData(0);for(let i=0;i<len;i++)data[i]=(Math.random()*2-1)*.28;const noise=audioCtx.createBufferSource(),filter=audioCtx.createBiquadFilter(),ng=audioCtx.createGain();noise.buffer=buf;noise.loop=true;filter.type='lowpass';filter.frequency.value=680;ng.gain.value=.032;o1.connect(g1).connect(master);o2.connect(g2).connect(master);noise.connect(filter).connect(ng).connect(master);master.connect(audioCtx.destination);o1.start();o2.start();noise.start();ambient={master,o1,o2,noise};ambientOn=true;$('#soundToggle').classList.add('active');$('#soundToggle').textContent='關閉靜心音'}function stopAmbient(){if(!ambient)return;const now=audioCtx.currentTime;ambient.master.gain.exponentialRampToValueAtTime(.0001,now+.8);setTimeout(()=>{try{ambient.o1.stop();ambient.o2.stop();ambient.noise.stop()}catch{}ambient=null},900);ambientOn=false;$('#soundToggle').classList.remove('active');$('#soundToggle').textContent='播放靜心音'}function chime(){ensureAudio();const now=audioCtx.currentTime,m=audioCtx.createGain();m.gain.setValueAtTime(.0001,now);m.gain.exponentialRampToValueAtTime(.12,now+.02);m.gain.exponentialRampToValueAtTime(.0001,now+1.4);[880,1320,1760].forEach((f,i)=>{const o=audioCtx.createOscillator(),g=audioCtx.createGain();o.type=i?'triangle':'sine';o.frequency.setValueAtTime(f,now);g.gain.value=i?.2:.55;o.connect(g).connect(m);o.start(now+i*.025);o.stop(now+1.45)});m.connect(audioCtx.destination)}function ascend(){ensureAudio();const now=audioCtx.currentTime,m=audioCtx.createGain(),o=audioCtx.createOscillator(),h=audioCtx.createOscillator();m.gain.setValueAtTime(.0001,now);m.gain.exponentialRampToValueAtTime(.12,now+.18);m.gain.exponentialRampToValueAtTime(.0001,now+2.8);o.type='sine';h.type='triangle';o.frequency.setValueAtTime(330,now);o.frequency.exponentialRampToValueAtTime(880,now+2.4);h.frequency.setValueAtTime(660,now);h.frequency.exponentialRampToValueAtTime(1320,now+2.5);o.connect(m);h.connect(m);m.connect(audioCtx.destination);o.start(now);h.start(now+.08);o.stop(now+2.9);h.stop(now+2.9)}
function toggleBreath(){breathOn=!breathOn;$('#breathOverlay').classList.toggle('hidden',!breathOn);$('#breathToggle').classList.toggle('active',breathOn);if(!breathOn){clearInterval(breathTimer);return}let steps=[['吸氣',4],['停留',4],['吐氣',6]],i=0,left=steps[0][1];function tick(){$('#breathText').textContent=steps[i][0];$('#breathCount').textContent=left;left--;if(left<0){i=(i+1)%steps.length;left=steps[i][1]}}tick();breathTimer=setInterval(tick,1000)}
addEventListener('pointermove',e=>{pointer.x=e.clientX;pointer.y=e.clientY;tooltip(findWish(e.clientX,e.clientY))});addEventListener('pointerdown',e=>{if(e.target.closest('button')||e.target.closest('select')||e.target.closest('.wish-panel')||e.target.closest('.side-panel')||e.target.closest('.story-card')||e.target.closest('label'))return;const w=findWish(e.clientX,e.clientY);if(w){tooltip(w);const s=storyFrom(w.index);if(s){$('#storyText').textContent=s;$('#storyCard').classList.remove('hidden');$('#storyCard').setAttribute('aria-hidden','false')}return}shoot(e.clientX,e.clientY);setTimeout(openPanel,560)});addEventListener('deviceorientation',e=>{if(typeof e.gamma==='number'){pointer.x=W/2+Math.max(-30,Math.min(30,e.gamma))*9;pointer.y=H/2+Math.max(-30,Math.min(30,e.beta))*6}});
$('#submitWish').onclick=submit;$('#cancelWish').onclick=closePanel;$('#wishInput').onkeydown=e=>{if(e.key==='Enter')submit();if(e.key==='Escape')closePanel()};$('#soundToggle').onclick=()=>ambientOn?stopAmbient():startAmbient();$('#breathToggle').onclick=toggleBreath;$('#statsToggle').onclick=()=>{$('#journalPanel').classList.add('show');$('#journalPanel').setAttribute('aria-hidden','false');renderAllJournal()};$('#closeJournal').onclick=()=>{$('#journalPanel').classList.remove('show');$('#journalPanel').setAttribute('aria-hidden','true')};$('#closeStory').onclick=()=>{$('#storyCard').classList.add('hidden');$('#storyCard').setAttribute('aria-hidden','true')};$('#clearBtn').onclick=async()=>{if(confirm('確定清空這台裝置的所有心願星星嗎？')){await clearWishes();saved=[];drawSaved();renderAllJournal();burst(W/2,H/2,'rgba(180,200,220,');toast('已清空本機星空')}};$('#exportBtn').onclick=exportJSON;$('#importInput').onchange=e=>{const f=e.target.files[0];if(f)importJSON(f);e.target.value=''};$$('.tab').forEach(b=>b.onclick=()=>{$$('.tab').forEach(x=>x.classList.remove('active'));b.classList.add('active');currentTab=b.dataset.tab;$$('.tab-page').forEach(p=>p.classList.remove('show'));$(`#tab-${currentTab}`).classList.add('show');renderAllJournal()});$('#themeSelect').onchange=async e=>{document.body.dataset.theme=e.target.value;await putMeta('theme',e.target.value);toast(`已切換：${themeNames[e.target.value]}`)};
addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredPrompt=e;$('#installBtn').classList.remove('hidden')});$('#installBtn').onclick=async()=>{if(!deferredPrompt)return;deferredPrompt.prompt();await deferredPrompt.userChoice;deferredPrompt=null;$('#installBtn').classList.add('hidden')};window.addEventListener('online',()=>$('#offlineBadge').classList.add('hidden'));window.addEventListener('offline',()=>$('#offlineBadge').classList.remove('hidden'));
function loop(t=0){sceneCtx.clearRect(0,0,W,H);bg(t);updateShooting();updateFloating();updateParticles();requestAnimationFrame(loop)}async function init(){db=await openDB();renderMood();saved=await getAllWishes();const theme=await getMeta('theme','midnight');document.body.dataset.theme=theme;$('#themeSelect').value=theme;resize();renderAllJournal();checkAchievements();loop();if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js');if(!navigator.onLine)$('#offlineBadge').classList.remove('hidden');setTimeout(()=>burst(W/2,H*.55,'rgba(160,180,205,'),500)}init().catch(e=>alert('初始化 IndexedDB 失敗：'+e.message));